name: ReactJS CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
    - run: npm ci
    - run: |
        git remote set-url origin https://shanenoi:${{ secrets.WRITE_TOKEN }}@github.com/shanenoi/noti-client
        git config user.email "shanenoi.org@gmail.com" && git config user.name "shanenoi"
        npm run predeploy
        npm run deploy
